spring:
  application:
    name: AIH
  
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/ai_hire?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000ms
          multiplier: 2

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Custom Configs
app:
  frontend-url: "${APP_FRONTEND_URL:http://localhost:5173}"
  jwt:
    secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    access-token-expiration: 3600
    refresh-token-expiration: 86400
  minio:
    endpoint: "${MINIO_ENDPOINT:http://localhost:9000}"
    accessKey: "${MINIO_ACCESS_KEY:minioadmin}"
    secretKey: "${MINIO_SECRET_KEY:minioadmin}"
    bucket: "${MINIO_BUCKET:ai-hire-resumes}"
  gemini:
    api-key: "${GEMINI_API_KEY:AIzaSyAIw2jm5GclwW5c_bjQnIbWl-hUJgQG4C8}"
    api-url: "${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent}"
    model-name: "${GEMINI_MODEL_NAME:gemini-3.1-flash-lite}"
    prompt-version: "${GEMINI_PROMPT_VERSION:v1.0}"

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    display-query-params-encoding: true
    operations-sorter: alpha
    tags-sorter: alpha
